INSERT INTO author (name) VALUES ('C.S. Lewis'),
('Roderick Beaton'),
('Aldous Huxley'),
('Harper Lee'),
('Paulo Coelho'),
('Jo Nesbø'),
('Agatha Christie'),
('Alexander Thompson'),
('Misha Glenny'),
('Charles Darwin'),
('Steven Runciman'),
('Thucydides'),
('Jane Austen'),
('Richard Dawkins'),
('Kostas Vlassopoulos'),
('Julian Barnes'),
('Thomas S. Kuhn'),
('Stieg Larsson'),
("Madeleine L'Engle"),
('J.D. Salinger'),
('Carl Sagan'),
('Louis Sachar'),
('Brian Greene'),
('R.J. Palacio'),
('Simon Singh'),
('Dan Brown'),
('Jennifer Ackerman'),
('Frances Hodgson Burnett'),
('Suzanne Collins'),
('Philip Pullman'),
('George Orwell'),
('Oscar Wilde'),
('Richard Clogg'),
('John Green'),
('Lois Lowry'),
('J.R.R. Tolkien'),
('Stephen Hawking'),
('Nikos Kazantzakis'),
('James D. Watson'),
('F. Scott Fitzgerald'),
('J.K. Rowling'),
('Carlos Ruiz Zafón'),
('Rick Riordan'),
('Emily Adams'),
('Elizabeth Kolbert'),
('Craig Childs'),
('Sy Montgomery'),
('David Brewer'),
('Marc Bekoff'),
('Elena Ferrante'),
('Peter Wohlleben'),
('Rosamund Young'),
('Sofka Zinovieff'),
('Yanis Varoufakis'),
('Michael Llewellyn Smith'),
('Muriel Barbery'),
('Albert Camus'),
('Alain Damasio'),
('Victor Hugo'),
('Charles Baudelaire'),
('Antoine de Saint-Exupéry'),
('Guy de Maupassant'),
('Choderlos de Laclos'),
('Michael Davis'),
('Sophia Johnson'),
('Alex Martinez'),
('Olivia Wilson'),
('David Thompson'),
('Isabella Anderson'),
('Matthew Harris'),
('Sophia Smith'),
('Katerina Gogou'),
('Dimitris Papadimitriou'),
('Vassilis Vassilikos'),
('Victoria Hislop'),
('Sophia Nikolaidou'),
('Kostas Skandalis'),
('Christos Georgiou'),
('Manolis Papagrigorakis'),
('Michalis Axenides'),
('Vassilis Koliatsos'),
('Konstantinos Dimas'),
('Nikos Papamichael'),
('Dimitrios Christodoulou');