ALTER TABLE author_book
ADD CONSTRAINT fk_book FOREIGN KEY (ISBN)
REFERENCES books (ISBN) ON DELETE RESTRICT ON UPDATE CASCADE

ALTER TABLE author_book
ADD CONSTRAINT fk_author FOREIGN KEY (author_id)
REFERENCES author(author_id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE users
ADD CONSTRAINT fk_school FOREIGN KEY (school_id)
REFERENCES schools(school_id) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE book_category
ADD CONSTRAINT fk_book_cat FOREIGN KEY (ISBN)
REFERENCES books(ISBN) ON DELETE RESTRICT ON UPDATE CASCADE;


ALTER TABLE book_category
ADD CONSTRAINT fk_category FOREIGN KEY (category_id)
REFERENCES category(category_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE book_school
ADD CONSTRAINT fk_book_sch FOREIGN KEY (ISBN)
REFERENCES books(ISBN) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE book_school
ADD CONSTRAINT fk_school_bk FOREIGN KEY (school_id)
REFERENCES schools(school_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE reviews
ADD CONSTRAINT fk_review_us FOREIGN KEY (id_user)
REFERENCES users(id_user) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE reviews
ADD CONSTRAINT fk_review_bk FOREIGN KEY (ISBN)
REFERENCES books(ISBN) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE lending
ADD CONSTRAINT fk_lending_us FOREIGN KEY (id_user)
REFERENCES users(id_user) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE lending
ADD CONSTRAINT fk_lending_book FOREIGN KEY (ISBN)
REFERENCES books(ISBN) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE lending
ADD CONSTRAINT fk_lending_sch FOREIGN KEY (school_id)
REFERENCES schools(school_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE booking
ADD CONSTRAINT fk_booking_us FOREIGN KEY (id_user)
REFERENCES users(id_user) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE booking
ADD CONSTRAINT fk_booking_book FOREIGN KEY (ISBN)
REFERENCES books(ISBN) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE booking
ADD CONSTRAINT fk_booking_sch FOREIGN KEY (school_id)
REFERENCES schools(school_id) ON DELETE RESTRICT ON UPDATE CASCADE;







