INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Great Gatsby', 'Scribner', 'F. Scott Fitzgerald', '9780743273565', 180, 'The story primarily concerns the young and mysterious millionaire Jay Gatsby and his quixotic passion and obsession with the beautiful former debutante Daisy Buchanan. ', 'English', 'Classic, Romance'),
('To Kill a Mockingbird', 'J. B. Lippincott & Co.', 'Harper Lee', '9780061120084', 281, 'The story takes place during three years of the Great Depression in the fictional "tired old town" of Maycomb, Alabama.', 'English', 'Classic, Social justice'),
('Harry Potter and the Philosopher''s Stone', 'Bloomsbury Publishing', 'J.K. Rowling', '9780747532743', 223, 'Harry Potter has been living a miserable life with his Aunt Petunia and Uncle Vernon. ', 'English', 'Fantasy, Magic'),
('Pride and Prejudice', 'T. Egerton, Whitehall', 'Jane Austen', '9780141439518', 279, 'The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book, who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.', 'English', 'Classic, Romance, Society'),
('The Catcher in the Rye', 'Little, Brown and Company', 'J.D. Salinger', '9780316769488', 224, 'The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school.', 'English', 'Coming-of-age, Society'),
('1984', 'Secker and Warburg', 'George Orwell', '9780451524935', 328, 'The story takes place in an imagined future, the year 1984, when much of the world has fallen victim to perpetual war, omnipresent government surveillance, historical negationism, and propaganda.', 'English', 'Dystopian, Political fiction'),
('Animal Farm', 'Secker and Warburg', 'George Orwell', '9780451526342', 112, 'The novel tells the story of a group of farm animals who rebel against their human farmer, hoping to create a society where the animals can be equal, free, and happy.', 'English', 'Political satire, Allegory'),
('Brave New World', 'Chatto & Windus', 'Aldous Huxley', '9780060850524', 288, 'The novel anticipates developments in reproductive technology, sleep-learning, psychological manipulation, and classical conditioning that are combined to make a dystopian society which is challenged by only a single individual: the storys protagonist.', 'English', 'Dystopian, Science fiction'),
('The Hobbit', 'George Allen & Unwin', 'J.R.R. Tolkien', '9780547928227', 310, 'The story is set in a world filled with magical creatures and tells the tale of a hobbit named Bilbo Baggins who is recruited by a wizard named Gandalf to help a group of dwarves reclaim their home and treasure from a dragon.', 'English', 'Fantasy, Adventure');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Hunger Games', 'Scholastic Press', 'Suzanne Collins', '9780439023481', 374, 'The Hunger Games is set in a post-apocalyptic dystopian world where the Capitol, a wealthy and technologically advanced city, holds power over the rest of the nation. Each year, the Capitol holds the Hunger Games, a televised event where one boy and one girl from each of the 12 districts must fight to the death.', 'English', 'Dystopian, Action'),
('The Girl with the Dragon Tattoo', 'Norstedts Förlag', 'Stieg Larsson', '9780307269751', 600, 'The novel tells the story of Mikael Blomkvist, a journalist who is hired to investigate the disappearance of a wealthy businessman''s niece, and Lisbeth Salander, a brilliant but troubled computer hacker who helps him with the investigation.', 'Swedish', 'Mystery, Thriller'),
('The Da Vinci Code', 'Doubleday', 'Dan Brown', '9780385504201', 454, 'The novel follows symbologist Robert Langdon and cryptologist Sophie Neveu as they investigate a murder in the Louvre Museum in Paris, and discover a trail of clues that lead them to a secret society and a religious mystery that could shake the foundations of Christianity.', 'English', 'Mystery, Thriller'),
('The Alchemist', 'HarperCollins', 'Paulo Coelho', '9780061122415', 208, 'The Alchemist follows the journey of an Andalusian shepherd boy named Santiago who dreams of discovering a treasure hidden in the Egyptian pyramids. Along the way, he meets a series of characters who teach him important lessons about life and love.', 'English', 'Fable, Quest'),
('The Fault in Our Stars', 'Dutton Books', 'John Green', '9780525478812', 313, 'The Fault in Our Stars is a love story between two teenagers with cancer, Hazel and Gus. Despite the challenges they face, they find love and hope in each other, and embark on a journey to Amsterdam to meet their favorite author.', 'English', 'Romance, Drama'),
('The Chronicles of Narnia', 'Geoffrey Bles', 'C.S. Lewis', '9780007117307', 767, 'The Chronicles of Narnia is a series of seven fantasy novels set in the fictional world of Narnia. The books tell the story of a group of children who discover a magical wardrobe that leads them to a world filled with talking animals, mythical creatures, and epic battles between good and evil.', 'English', 'Fantasy, Adventure'),
('The Picture of Dorian Gray', 'Lippincott''s Monthly Magazine', 'Oscar Wilde', '9780486278070', 254, 'The novel tells the story of a young man named Dorian Gray who becomes obsessed with his own beauty and youth. He sells his soul to the devil in exchange for eternal youth, and his portrait ages instead of him. As he becomes more and more corrupt, the portrait becomes more and more grotesque.', 'English', 'Gothic, Horror');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Scapegoat', 'Ypsilon', 'Sophia Nikolaidou', '9789601425009', 384, 'The Scapegoat is a contemporary novel set in Athens during the Greek economic crisis. The story follows the lives of three characters whose paths intersect as they struggle to survive in a society that is collapsing around them.', 'Greek', 'Contemporary, Economic Crisis'),
('Austerity Measures', 'Serpent''s Tail', 'Yanis Varoufakis', '9781846689953', 320, 'Austerity Measures is a collection of essays by Yanis Varoufakis, the former finance minister of Greece. The book offers a critical analysis of the European Union''s response to the Greek debt crisis, and argues for an alternative approach to economics and politics.', 'Greek', 'Politics, Economics'),
('The Last Temptation', 'Faber & Faber', 'Nikos Kazantzakis', '9780571321715', 608, 'The Last Temptation is a novel that reimagines the life of Jesus Christ. The book explores themes of faith, doubt, and the nature of sacrifice, and caused controversy upon its publication due to its controversial portrayal of Christ.', 'Greek', 'Fiction, Religion'),
('Christ Recrucified', 'Faber & Faber', 'Nikos Kazantzakis', '9780571321708', 496, 'Christ Recrucified is a novel that tells the story of a small Greek village that stages a Passion Play. The book explores themes of faith, sacrifice, and the human condition, and is considered one of Kazantzakis''s masterpieces.', 'Greek', 'Fiction, Religion'),
('The Greek War of Independence: The Struggle for Freedom from Ottoman Oppression', 'Open Road Media', 'David Brewer', '9781480437678', 576, 'The Greek War of Independence is a comprehensive history of the Greek Revolution against Ottoman rule in the early 19th century. The book explores the political, social, and cultural factors that led to the rebellion, and the impact it had on Greece and the wider world.', 'English', 'History, Greece');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('Zorba the Greek', 'Simon & Schuster', 'Nikos Kazantzakis', '9780684825546', 320, 'A novel about the friendship between a young intellectual and a passionate Greek peasant named Zorba.', 'Greek', 'Fiction, Philosophy, Friendship'),
('Report to Greco', 'Faber & Faber', 'Nikos Kazantzakis', '9780571229214', 576, 'An autobiographical novel that explores the author''s personal and philosophical journey.', 'Greek', 'Autobiography, Philosophy, Religion'),
('The Odyssey: A Modern Sequel', 'Simon & Schuster', 'Nikos Kazantzakis', '9780684169964', 928, 'A poetic epic that continues the story of Odysseus after his return to Ithaca.', 'Greek', 'Poetry, Epic, Mythology'),
('The Saviors of God: Spiritual Exercises', 'Simon & Schuster', 'Nikos Kazantzakis', '9780684834951', 256, 'A philosophical and spiritual exploration of the author''s beliefs and values.', 'Greek', 'Philosophy, Spirituality, Religion'),
('Saint Francis', 'Simon & Schuster', 'Nikos Kazantzakis', '9780684841263', 384, 'A novel about the life of Saint Francis of Assisi, told in a lyrical and imaginative style.', 'Greek', 'Fiction, Religion, Biography'),
('The Greek Passion', 'Faber & Faber', 'Nikos Kazantzakis', '9780571207045', 448, 'A novel about a Greek village that takes in refugees from a nearby town, leading to a conflict between the villagers and the refugees.', 'Greek', 'Fiction, Social Commentary, Philosophy'),
('Toda Raba', 'C. Hurst & Co.', 'Nikos Kazantzakis', '9781849048134', 120, 'A collection of essays, poems, and letters that express the author''s ideas and beliefs about life, art, and spirituality.', 'Greek', 'Essays, Poetry, Letters');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Shadow of the Wind', 'Weidenfeld & Nicolson', 'Carlos Ruiz Zafón', '9780753820254', 512, 'The Shadow of the Wind is a gothic novel set in Barcelona in the aftermath of the Spanish Civil War. The story follows young Daniel Sempere as he becomes obsessed with a mysterious book and its enigmatic author. The book has been translated into many languages and is considered a modern classic.', 'English', 'Fiction, Spain, Gothic'),
('The Elegance of the Hedgehog', 'Europa Editions', 'Muriel Barbery', '9781933372600', 336, 'The Elegance of the Hedgehog is a philosophical novel set in an apartment building in Paris. The story follows the lives of two unlikely friends, a precocious twelve-year-old girl and a reclusive concierge, as they contemplate the meaning of life and death. The book has been translated into many languages and was a bestseller in France.', 'English', 'Fiction, Philosophy, France'),
('My Brilliant Friend', 'Europa Editions', 'Elena Ferrante', '9781609450786', 336, 'My Brilliant Friend is a coming-of-age novel set in Naples, Italy. The story follows the lives of two young girls, Elena and Lila, as they grow up in a poor neighborhood and navigate the complexities of friendship, family, and education. The book is the first in a series of four novels.', 'English', 'Fiction, Italy, Coming-of-Age'),
('The Sense of an Ending', 'Jonathan Cape', 'Julian Barnes', '9780224094153', 150, 'The Sense of an Ending is a novel about memory, regret, and the nature of truth. The story follows retired divorcee Tony Webster as he reflects on his life and the events that led to a tragic incident in his youth. The book won the Man Booker Prize in 2011.', 'English', 'Fiction, Memory, Truth, England');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES 
('L''étranger', 'Gallimard', 'Albert Camus', '9782070360024', 123, 'A novel about the indifference of man towards life and death, told through the eyes of Meursault, a detached and apathetic character.', 'French', 'Novel, Philosophy, Existentialism'),
('Les Misérables', 'Gallimard', 'Victor Hugo', '9782070401834', 1952, 'A historical novel about the life of Jean Valjean, a former convict who tries to redeem himself and help others, despite the oppression and poverty that surround him.', 'French', 'Historical novel, French literature, Poverty'),
('Le Petit Prince', 'Gallimard', 'Antoine de Saint-Exupéry', '9782070612758', 96, 'A poetic tale about friendship and life, told through the adventures of a little prince from another planet.', 'French', 'Tale, Philosophy, Friendship'),
('Les Fleurs du Mal', 'Gallimard', 'Charles Baudelaire', '9782070409274', 448, 'A collection of dark and sensual poems that explore the themes of love, death, and modernity.', 'French', 'Poetry, French literature, Spleen'),
('Bel-Ami', 'Le Livre de Poche', 'Guy de Maupassant', '9782253002381', 304, 'A novel about the social ascent of Georges Duroy, an ambitious and seductive young man, in the Paris of the late 19th century.', 'French', 'Novel, French literature, Ambition'),
('La Peste', 'Gallimard', 'Albert Camus', '9782070360420', 320, 'A novel about a plague epidemic that strikes the city of Oran, Algeria, and the reactions of the inhabitants to death and suffering.', 'French', 'Novel, Philosophy, Existentialism'),
('Les Liaisons dangereuses', 'Le Livre de Poche', 'Choderlos de Laclos', '9782253004224', 544, 'An epistolary novel about the games of seduction and power between two French aristocrats, the Marquise de Merteuil and the Vicomte de Valmont.', 'French', 'Epistolary novel, French literature, Seduction'),
('La Horde du Contrevent', 'Gallimard', 'Alain Damasio', '9782070361878', 656, 'A science-fiction novel about the adventures of a team of wind hunters, who try to reach the origin of the winds to discover the secret of their existence.', 'French', 'Science-fiction novel, Adventure, Philosophy');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Snowman', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780525432483', 464, 'The Snowman is a crime novel featuring the Norwegian detective Harry Hole. In this novel, Harry investigates a series of murders that are connected to the appearance of a snowman at the crime scenes. The novel was a bestseller and has been adapted into a film.', 'English', 'Crime fiction, Detective, Norway'),
('The Redbreast', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780062068422', 544, 'The Redbreast is the third novel featuring Harry Hole, and explores the connections between Norway\'s Nazi past and a series of murders. The novel was praised for its intricate plot and characterization.', 'English', 'Crime fiction, Detective, Norway'),
('Phantom', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780345807151', 496, 'Phantom is the ninth novel featuring Harry Hole, and deals with the aftermath of a bank robbery in Oslo. The novel was praised for its complex plot and the development of Harry\'s character.', 'English', 'Crime fiction, Detective, Norway'),
('The Bat', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780345807090', 384, 'The Bat is the first novel featuring Harry Hole, and takes place in Australia, where Harry is sent to investigate the murder of a Norwegian citizen. The novel explores themes of culture clash and identity.', 'English', 'Crime fiction, Detective, Australia'),
('The Thirst', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780525432322', 544, 'The Thirst is the eleventh novel featuring Harry Hole, and deals with a series of murders that appear to be connected to the vampire mythology. The novel was praised for its twists and the return of some familiar characters from the series.', 'English', 'Crime fiction, Detective, Norway');

-- Insert statement 1  -------OK
INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('Murder on the Orient Express', 'HarperCollins', 'Agatha Christie', '9780062693662', 256, 'A classic detective novel featuring Hercule Poirot', 'English', 'Fiction, Mystery, Detective'),
('And Then There Were None', 'HarperCollins', 'Agatha Christie', '9780062073488', 272, 'A suspenseful murder mystery on an isolated island', 'English', 'Fiction, Mystery, Suspense'),
('Death on the Nile', 'HarperCollins', 'Agatha Christie', '9780062073556', 352, 'A thrilling murder mystery set aboard a luxury cruise ship', 'English', 'Fiction, Mystery, Detective'),
('The A.B.C. Murders', 'HarperCollins', 'Agatha Christie', '9780062073587', 256, 'A race against time to catch a serial killer', 'English', 'Fiction, Mystery, Detective'),
('Murder at the Vicarage', 'HarperCollins', 'Agatha Christie', '9780062073617', 288, 'The first Miss Marple mystery novel', 'English', 'Fiction, Mystery, Detective'),
('The Mousetrap', 'HarperCollins', 'Agatha Christie', '9780062073778', 128, 'A play by Agatha Christie, the longest-running in the world', 'English', 'Fiction, Mystery, Drama'),
('Five Little Pigs', 'HarperCollins', 'Agatha Christie', '9780062073693', 304, 'A cold case mystery involving a murder from the past', 'English', 'Fiction, Mystery, Detective');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Leopard', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780099546790', 640, 'The Leopard is the eighth novel featuring Harry Hole, and involves the investigation of a series of murders that are linked to a notorious Norwegian serial killer. The novel was praised for its suspenseful plot and detailed characterization of Harry.', 'English', 'Crime fiction, Detective, Norway'),
('Police', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780307960498', 640, 'Police is the tenth novel featuring Harry Hole, and deals with a series of killings that appear to be linked to a case that Harry investigated years ago. The novel was praised for its dark and twisty plot and the return of some beloved characters from the series.', 'English', 'Crime fiction, Detective, Norway'),
('The Son', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780307960474', 400, 'The Son is a standalone novel by Jo Nesbø that follows the story of a young man who is serving time in prison for crimes he did not commit. When he is released, he sets out to find the people who set him up and clear his name. The novel was praised for its suspenseful plot and its exploration of themes like justice and revenge.', 'English', 'Suspense fiction, Norway'),
('Headhunters', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780307948687', 288, 'Headhunters is a standalone novel by Jo Nesbø that follows the story of Roger Brown, a successful headhunter who is also an art thief. When he tries to steal a valuable painting from one of his clients, he gets more than he bargained for. The novel was praised for its fast-paced plot and its memorable protagonist.', 'English', 'Suspense fiction, Art theft, Norway'),
('The Redeemer', 'Vintage Crime/Black Lizard', 'Jo Nesbø', '9780099546776', 464, 'The Redeemer is the sixth novel featuring Harry Hole, and involves the investigation of a series of murders that appear to be linked to a Salvation Army mission in Oslo. The novel was praised for its atmospheric setting and its complex plot.', 'English', 'Crime fiction, Detective, Norway');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('Z', 'Kedros', 'Vassilis Vassilikos', '9789600432437', 250, 'Z is a political novel set in Greece during the 1960s and follows the investigation of a murder of a left-wing activist. The novel explores themes of political corruption and the abuse of power. It was adapted into an Oscar-nominated film directed by Costa-Gavras.', 'Greek', 'Political fiction, Historical fiction, Film adaptation'),
('The Island', 'Kedros', 'Victoria Hislop', '9789600432895', 472, 'The Island is a novel set on the Greek island of Spinalonga, which was once a leper colony. The novel follows the story of a young woman who discovers her familys connection to the island and its inhabitants. The novel has been translated into over 25 languages and was adapted into a television series.', 'Greek', 'Historical fiction, Romance, Family saga, Television adaptation'),
('The Return', 'Kedros', 'Dimitris Papadimitriou', '9789600419247', 265, 'The Return is a novel that explores the lives of a group of Greek immigrants living in Germany. The novel follows the story of a young woman who returns to Greece to search for her missing father. The novel deals with themes of identity, culture, and the immigrant experience.', 'Greek', 'Contemporary fiction, Immigrant literature'),
('The Last Word', 'Kedros', 'Katerina Gogou', '9789600415584', 150, 'The Last Word is a collection of short stories by Katerina Gogou, a prominent figure in the Greek counterculture movement. The stories are dark and gritty, and deal with themes of poverty, addiction, and social injustice. The collection is considered a classic of modern Greek literature.', 'Greek', 'Short stories, Counterculture, Social realism'),
('The House on Paradise Street', 'Head of Zeus', 'Sofka Zinovieff', '9781781855869', 368, 'The House on Paradise Street is a novel set in Athens during the Second World War and the Greek Civil War. The novel follows the story of a young woman who becomes involved with the resistance movement and must navigate the dangerous political landscape of the time. The novel deals with themes of love, betrayal, and survival.', 'English', 'Historical fiction, War fiction, Resistance, Greece');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES 
('A Brief History of Time', 'Bantam Books', 'Stephen Hawking', '9780553380163', 212, 'An introduction to cosmology and the history of the universe, written for the layperson.', 'English', 'Cosmology, Physics, Astronomy'),
('The Selfish Gene', 'Oxford University Press', 'Richard Dawkins', '9780199291151', 384, 'A book about the evolution of biological life, with a focus on the role of genes in the process of natural selection.', 'English', 'Evolution, Genetics, Biology'),
('The Double Helix', 'Scribner', 'James D. Watson', '9780684803355', 256, 'A memoir about the discovery of the structure of DNA, written by one of its co-discoverers.', 'English', 'DNA, Genetics, Memoir'),
('The Elegant Universe', 'Vintage Books', 'Brian Greene', '9780375708114', 448, 'A book about the history of physics, from classical mechanics to string theory and beyond.', 'English', 'Physics, String theory, Cosmology'),
('The Demon-Haunted World', 'Ballantine Books', 'Carl Sagan', '9780345409461', 480, 'A book about the scientific method and the importance of critical thinking in a world of pseudoscience and superstition.', 'English', 'Science, Critical thinking, Skepticism'),
('The Structure of Scientific Revolutions', 'University of Chicago Press', 'Thomas S. Kuhn', '9780226458083', 212, 'A book about the history and philosophy of science, with a focus on the role of paradigm shifts in scientific progress.', 'English', 'Philosophy of science, History of science, Scientific progress'),
('The Origin of Species', 'Penguin Classics', 'Charles Darwin', '9780140439120', 480, 'A book about the theory of evolution by natural selection, written by its founder and first proponent.', 'English', 'Evolution, Natural selection, Biology'),
('The Code Book', 'Doubleday', 'Simon Singh', '9780385495318', 432, 'A book about the history and science of cryptography, from ancient times to the present day.', 'English', 'Cryptography, History of science, Computer science');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES 
('Electromagnetism', 'Patakis Publishers', 'Kostas Skandalis', '9789601660105', 448, 'A textbook on electromagnetism, covering the theory and applications of electromagnetic fields and waves.', 'Greek', 'Physics, Electromagnetism, Electrical engineering'),
('Cosmogony: The Birth of the Universe', 'Patakis Publishers', 'Christos Georgiou', '9789601662741', 320, 'A book on the origin and evolution of the universe, covering topics such as the big bang, cosmic inflation, and dark matter.', 'Greek', 'Cosmology, Astronomy, Astrophysics'),
('Anatomy of the Nervous System', 'Paschalidis Medical Publications', 'Vassilis Koliatsos', '9789603991473', 472, 'A comprehensive textbook on the anatomy and physiology of the nervous system, including the brain, spinal cord, and peripheral nerves.', 'Greek', 'Neuroscience, Anatomy, Physiology'),
('Elementary Differential Equations', 'Ellinika Grammata', 'Nikos Papamichael', '9789604062389', 480, 'A textbook on differential equations, covering topics such as first-order equations, linear equations, and Laplace transforms.', 'Greek', 'Mathematics, Differential equations, Calculus'),
('The Quantum Theory of Fields', 'Themelio Publications', 'Michalis Axenides', '9789603103397', 640, 'A textbook on the quantum theory of fields, covering topics such as gauge theories, renormalization, and the Higgs mechanism.', 'Greek', 'Physics, Quantum field theory, Particle physics'),
('The Brain', 'Patakis Publishers', 'Manolis Papagrigorakis', '9789601663069', 352, 'A book on the structure and function of the brain, covering topics such as neuroplasticity, memory, and consciousness.', 'Greek', 'Neuroscience, Brain, Psychology'),
('General Relativity and Cosmology', 'Papazisi Publishers', 'Dimitrios Christodoulou', '9789604587546', 576, 'A textbook on general relativity and cosmology, covering topics such as black holes, gravitational waves, and the expanding universe.', 'Greek', 'Physics, General relativity, Cosmology'),
('Biochemistry and Pathobiochemistry', 'Paschalidis Medical Publications', 'Konstantinos Dimas', '9789603995044', 532, 'A textbook on biochemistry and pathobiochemistry, covering topics such as metabolism, enzymes, and cellular signaling.', 'Greek', 'Biochemistry, Pathology, Molecular biology');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('Percy Jackson and The Lightning Thief', 'Disney Hyperion', 'Rick Riordan', '9781423106977', 375, 'Percy Jackson and The Lightning Thief is a fantasy adventure novel about a young boy named Percy who discovers he is the son of Poseidon, the Greek god of the sea. He goes on a quest to retrieve Zeus''s stolen lightning bolt and clear his name. The novel deals with themes of Greek mythology, friendship, and bravery.', 'English', 'Children''s literature, Fantasy, Adventure, Greek mythology'),
('A Wrinkle in Time', 'Farrar, Straus and Giroux', 'Madeleine L''Engle', '9780312367541', 211, 'A Wrinkle in Time is a science fantasy novel about a young girl named Meg Murry who travels through space and time to save her father from a malevolent force. The novel deals with themes of family, love, and the power of good over evil.', 'English', 'Children''s literature, Science fantasy, Time travel, Family'),
('The Giver', 'Houghton Mifflin', 'Lois Lowry', '9780544336261', 225, 'The Giver is a dystopian novel about a boy named Jonas who lives in a seemingly perfect society where everything is controlled by the government. When he is chosen to be the Receiver of Memory, he begins to question the morality of his society. The novel deals with themes of individuality, freedom, and the value of memories.', 'English', 'Children''s literature, Dystopian fiction, Science fiction, Individuality'),
('The Golden Compass', 'Knopf Books for Young Readers', 'Philip Pullman', '9780440418320', 399, 'The Golden Compass is a fantasy novel about a young girl named Lyra who embarks on a dangerous journey to save her friend and uncover the truth about a mysterious substance called Dust. The novel deals with themes of religion, freedom, and the power of knowledge.', 'English', 'Children''s literature, Fantasy, Adventure, Religion'),
('Holes', 'Farrar, Straus and Giroux', 'Louis Sachar', '9780374332662', 233, 'Holes is a mystery novel about a boy named Stanley who is sent to a juvenile detention center where he and his fellow inmates are forced to dig holes in the desert. As he digs, Stanley uncovers the truth about the center and his family''s past. The novel deals with themes of family, friendship, and justice.', 'English', 'Children''s literature, Mystery, Adventure, Justice'),
('The Secret Garden', 'Heinemann', 'Frances Hodgson Burnett', '9780435123653', 263, 'The Secret Garden is a children''s novel about a young girl named Mary who moves to her uncle''s estate in England and discovers a hidden garden that has been locked up for years. The novel deals with themes of friendship, nature, and the power of positive thinking.', 'English', 'Children''s literature, Friendship, Nature, Positive thinking');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('The Art of Impressionism', 'Art Books Inc.', 'Emily Adams', '9781234567890', 200, 'An in-depth exploration of the Impressionist art movement', 'English', 'Art, Impressionism, Painting'),
       ('Contemporary Art: A Visual Journey', 'Art Publishers Ltd.', 'Michael Davis', '9782345678901', 180, 'A comprehensive survey of contemporary art from around the world', 'English', 'Art, Contemporary Art, Art History'),
       ('The Lives of the Artists', 'Art & Culture Press', 'Sophia Johnson', '9783456789012', 350, 'Biographies of famous artists throughout history', 'English', 'Art, Artists, Biographies'),
       ('The Art of Photography', 'Photography Books Ltd.', 'Alex Martinez', '9784567890123', 150, 'A guide to mastering the art of photography', 'English', 'Art, Photography, Camera Techniques'),
       ('Art Nouveau: A Style for the Modern Age', 'Art Publishers Inc.', 'Olivia Wilson', '9785678901234', 220, 'An exploration of the Art Nouveau movement in design and architecture', 'English', 'Art, Art Nouveau, Design'),
       ('Abstract Art: Exploring the Boundaries', 'Abstract Art Press', 'David Thompson', '9786789012345', 280, 'A comprehensive study of abstract art and its evolution', 'English', 'Art, Abstract Art, Art History'),
       ('Renaissance Art: The Age of Enlightenment', 'Art Books Ltd.', 'Isabella Anderson', '9787890123456', 300, 'A detailed examination of the art and culture of the Renaissance period', 'English', 'Art, Renaissance Art, European Art'),
       ('Sculpture: From Classical to Contemporary', 'Sculpture Publications', 'Matthew Harris', '9788901234567', 230, 'An overview of the history and techniques of sculpture', 'English', 'Art, Sculpture, Art History'),
       ('The Art of Color Theory', 'Art Color Press', 'Sophia Smith', '9789012345678', 180, 'An exploration of color theory in art and design', 'English', 'Art, Color Theory, Design'),
       ('Art and Society: A Cultural Perspective', 'Art & Culture Books', 'Alexander Thompson', '9780123456789', 250, 'An interdisciplinary examination of the relationship between art and society', 'English', 'Art, Society, Cultural Studies');
	   
INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES 
('A Concise History of Greece', 'Cambridge University Press', 'Richard Clogg', '9780521004794', 320, 'A comprehensive history of Greece from ancient times to the present day.', 'English', 'Greek history, ancient Greece, modern Greece'),
('Greece: Biography of a Modern Nation', 'Harper Perennial', 'Roderick Beaton', '9780007382161', 704, 'A vivid and expansive history of Greece from its earliest days to the present.', 'English', 'Greek history, modern Greece, Greek culture'),
('The Greeks: A Portrait of Self and Others', 'Oxford University Press', 'Kostas Vlassopoulos', '9780199672776', 304, 'Explores the ways in which ancient Greeks thought about themselves and their relationship to others.', 'English', 'Ancient Greece, Greek culture, Greek society'),
('The Peloponnesian War', 'Penguin Classics', 'Thucydides', '9780140440393', 648, 'An account of the war between Athens and Sparta in the 5th century BC.', 'English', 'Ancient Greece, Peloponnesian War, Athenian Empire'),
('The Fall of Constantinople 1453', 'Penguin Classics', 'Steven Runciman', '9780140440119', 400, 'A gripping account of the events that led to the fall of Constantinople to the Ottoman Turks.', 'English', 'Byzantine Empire, Ottoman Empire, history of Constantinople'),
('The Balkans: Nationalism, War and the Great Powers 1804-1999', 'Penguin Books', 'Misha Glenny', '9780140233773', 720, 'A comprehensive history of the Balkans, exploring the roots of nationalism and the conflicts that have plagued the region.', 'English', 'Balkan history, nationalism, Balkan wars'),
('The Greek Revolution: 1821 and the Freedom of the Nation', 'Verso', 'David Brewer', '9781844675639', 400, 'A history of the Greek War of Independence and its impact on the country and the wider world.', 'English', 'Greek War of Independence, Greek revolution, Ottoman Empire'),
('Athens: A Cultural and Literary History', 'Signal Books', 'Michael Llewellyn Smith', '9781904955768', 256, 'Explores the cultural and literary history of Athens, from ancient times to the present day.', 'English', 'Athens history, Greek literature, Greek culture');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES ('Percy Jackson and the Lightning Thief', 'Disney Hyperion Books', 'Rick Riordan', '9780786838653', 377, 'Percy Jackson and the Lightning Thief is a fantasy adventure novel about a young boy named Percy Jackson who discovers he is a demigod and embarks on a quest to retrieve Zeus''s stolen lightning bolt. The novel deals with themes of identity, friendship, and mythology.', 'English', 'Children''s literature, Fantasy, Adventure, Mythology'),
('The Lion, the Witch and the Wardrobe', 'Geoffrey Bles', 'C.S. Lewis', '9780064471046', 206, 'The Lion, the Witch and the Wardrobe is a classic fantasy novel about four siblings who discover a magical world called Narnia through a wardrobe in their home. The novel deals with themes of good versus evil, redemption, and sacrifice.', 'English', 'Children''s literature, Fantasy, Christian literature'),
('Wonder', 'Knopf Books for Young Readers', 'R.J. Palacio', '9780375869020', 316, 'Wonder is a novel about a young boy named August who has a facial deformity and starts attending public school for the first time. The novel deals with themes of kindness, empathy, and acceptance.', 'English', 'Children''s literature, Realistic fiction, Bullying, Disability'),
('The Secret Garden', 'Heinemann', 'Frances Hodgson Burnett', '9780590406712', 358, 'The Secret Garden is a classic children''s novel about a young girl named Mary who discovers a hidden garden on her uncle''s estate and befriends a sickly boy named Colin. The novel deals with themes of nature, friendship, and healing.', 'English', 'Children''s literature, Realistic fiction, Friendship, Nature');

INSERT INTO books (title, publisher, author, ISBN, page_number, summary, book_language, keywords)
VALUES 
('The Hidden Life of Trees', 'Greystone Books', 'Peter Wohlleben', '9781771642484', 288, 'A fascinating exploration of the complex social networks and communication systems of trees.', 'English', 'Trees, forests, nature'),
('The Soul of an Octopus', 'Atria Books', 'Sy Montgomery', '9781451697728', 272, 'A lyrical meditation on the nature of consciousness and the complex inner lives of these fascinating creatures.', 'English', 'Octopus, animal consciousness, marine biology'),
('The Genius of Birds', 'Penguin Books', 'Jennifer Ackerman', '9780399563126', 352, 'An engaging and insightful look at the intelligence and adaptability of birds.', 'English', 'Birds, animal behavior, bird intelligence'),
('The Emotional Lives of Animals', 'New World Library', 'Marc Bekoff', '9781577316493', 256, 'An exploration of the rich emotional lives of animals, from joy and grief to anger and love.', 'English', 'Animal emotions, animal behavior, animal cognition'),
('The Sixth Extinction: An Unnatural History', 'Picador', 'Elizabeth Kolbert', '9781250062185', 336, 'A sobering look at the mass extinctions happening on our planet and the role humans are playing in them.', 'English', 'Extinction, environmentalism, conservation'),
('The Secret Life of Cows', 'Greystone Books', 'Rosamund Young', '9781771643016', 160, 'A charming and intimate portrait of cows and their complex social lives, based on years of observation on a farm in England.', 'English', 'Cows, animal behavior, animal cognition'),
('The Animal Dialogues: Uncommon Encounters in the Wild', 'Scribner', 'Craig Childs', '9781416561111', 288, 'A collection of essays that explore the author\'s experiences with wild animals, from grizzly bears to mountain lions.', 'English', 'Wild animals, nature, animal behavior');